"""phase_5_optimization

Revision ID: 23fb1fa72d97
Revises: 66ed505c6a0a
Create Date: 2026-08-26 14:28:15.533982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23fb1fa72d97'
down_revision: Union[str, Sequence[str], None] = '66ed505c6a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_allocations',
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recommended_bed_id', sa.UUID(), nullable=True),
    sa.Column('recommended_doctor_id', sa.UUID(), nullable=True),
    sa.Column('recommended_department_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('RECOMMENDED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', name='allocationstatusenum'), nullable=False),
    sa.Column('constraints_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recommended_bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['recommended_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['recommended_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_allocations_admission_id'), 'resource_allocations', ['admission_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_patient_id'), 'resource_allocations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_recommended_bed_id'), 'resource_allocations', ['recommended_bed_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_recommended_department_id'), 'resource_allocations', ['recommended_department_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_recommended_doctor_id'), 'resource_allocations', ['recommended_doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_allocations_recommended_doctor_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_recommended_department_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_recommended_bed_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_patient_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_admission_id'), table_name='resource_allocations')
    op.drop_table('resource_allocations')
    sa.Enum(name='allocationstatusenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
