"""Phase 3 Policy Engine

Revision ID: 66ed505c6a0a
Revises: 57afa5e4bc92
Create Date: 2026-08-26 14:07:59.289362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ed505c6a0a'
down_revision: Union[str, Sequence[str], None] = '57afa5e4bc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_evaluation_audits',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('admission_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('policy_category', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matched_rules_json', sa.JSON(), nullable=True),
    sa.Column('failed_rules_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('required_documents_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluation_audits_admission_id'), 'policy_evaluation_audits', ['admission_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_audits_patient_id'), 'policy_evaluation_audits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_audits_user_id'), 'policy_evaluation_audits', ['user_id'], unique=False)
    op.add_column('policy_rules', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('policy_rules', sa.Column('priority', sa.Integer(), nullable=False))
    sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', name='policystatusenum').create(op.get_bind())
    op.add_column('policy_rules', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', name='policystatusenum'), nullable=False))
    op.add_column('policy_rules', sa.Column('effective_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('policy_rules', sa.Column('effective_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('policy_rules', sa.Column('requires_manual_review', sa.Boolean(), nullable=False))
    op.add_column('policy_rules', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_policy_rules_rule_code'), table_name='policy_rules')
    op.create_index(op.f('ix_policy_rules_rule_code'), 'policy_rules', ['rule_code'], unique=False)
    op.create_unique_constraint('uq_policy_rule_code_version', 'policy_rules', ['rule_code', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_policy_rule_code_version', 'policy_rules', type_='unique')
    op.drop_index(op.f('ix_policy_rules_rule_code'), table_name='policy_rules')
    op.create_index(op.f('ix_policy_rules_rule_code'), 'policy_rules', ['rule_code'], unique=True)
    op.drop_column('policy_rules', 'source_reference')
    op.drop_column('policy_rules', 'requires_manual_review')
    op.drop_column('policy_rules', 'effective_end_date')
    op.drop_column('policy_rules', 'effective_start_date')
    op.drop_column('policy_rules', 'status')
    op.drop_column('policy_rules', 'priority')
    op.drop_column('policy_rules', 'version')
    op.drop_index(op.f('ix_policy_evaluation_audits_user_id'), table_name='policy_evaluation_audits')
    op.drop_index(op.f('ix_policy_evaluation_audits_patient_id'), table_name='policy_evaluation_audits')
    op.drop_index(op.f('ix_policy_evaluation_audits_admission_id'), table_name='policy_evaluation_audits')
    op.drop_table('policy_evaluation_audits')
    # ### end Alembic commands ###
