"""phase_6_cdss

Revision ID: 72ccf6d0320c
Revises: 23fb1fa72d97
Create Date: 2026-08-26 14:43:57.386105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72ccf6d0320c'
down_revision: Union[str, Sequence[str], None] = '23fb1fa72d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdss_clinical_rules',
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('condition_logic', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='alertseverityenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdss_clinical_rules_rule_code'), 'cdss_clinical_rules', ['rule_code'], unique=True)
    op.create_table('cdss_guidelines',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('condition_category', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendation_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdss_evaluations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=True),
    sa.Column('clinician_review_required', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdss_evaluations_admission_id'), 'cdss_evaluations', ['admission_id'], unique=False)
    op.create_index(op.f('ix_cdss_evaluations_patient_id'), 'cdss_evaluations', ['patient_id'], unique=False)
    op.create_table('cdss_clinical_alerts',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='alertseverityenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('supporting_value', sa.String(length=255), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['cdss_evaluations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['cdss_clinical_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdss_medication_alerts',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='alertseverityenum'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['cdss_evaluations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdss_risk_assessments',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='riskcategoryenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['cdss_evaluations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdss_risk_assessments')
    op.drop_table('cdss_medication_alerts')
    op.drop_table('cdss_clinical_alerts')
    op.drop_index(op.f('ix_cdss_evaluations_patient_id'), table_name='cdss_evaluations')
    op.drop_index(op.f('ix_cdss_evaluations_admission_id'), table_name='cdss_evaluations')
    op.drop_table('cdss_evaluations')
    op.drop_table('cdss_guidelines')
    op.drop_index(op.f('ix_cdss_clinical_rules_rule_code'), table_name='cdss_clinical_rules')
    op.drop_table('cdss_clinical_rules')
    # ### end Alembic commands ###
